version: '3'
services: 
    mongo:
        image: mongo
        ports:
            - 27022:${MONGO_PORT}
        volumes:
            - ./mongo/db:/data/db
            - ./mongo/configdb:/data/configdb
            - ./mongo/init:/docker-entrypoint-initdb.d 
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: menuDB
    api: 
        build: .
        volumes: 
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 8080:8080
        command: node app
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: menuDB
networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}